const APP_ACTIONS_CONSTANTS = {
  SET_LOADING: 'SET_LOADING',
  REQUEST_LISTS: 'REQUEST_LISTS',

  // app
  APP_INIT: 'APP_INIT',
  SET_ERROR: 'SET_ERROR',
  SET_MODE: 'SET_MODE',
  SET_LANGUAGE: 'SET_LANGUAGE',
  CLEAR_ERROR: 'CLEAR_ERROR',
  CLEAR_STATE: 'CLEAR_STATE',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  SET_ALERT_VISIBLE: 'SET_ALERT_VISIBLE',
  GET_CONTACTS: 'GET_CONTACTS',
  SET_CONTACTS: 'SET_CONTACTS',

  // auth
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER: 'SET_USER',
  SET_TOKEN: 'SET_TOKEN',
};

export default APP_ACTIONS_CONSTANTS;
