export const TESTS_IDS_LOGIN = {
  TEST_ID_EMAIL_INPUT: 'TEST_ID_EMAIL_INPUT',
  TEST_ID_PASSWORD_INPUT: 'TEST_ID_PASSWORD_INPUT',
  TEST_ID_SUBMIT_BUTTON: 'TEST_ID_SUBMIT_BUTTON',
  TEST_ID_REMEMBER: 'TEST_ID_REMEMBER',
  TEST_ID_VALIDATION_ERROR_EMAIL: 'TEST_ID_VALIDATION_ERROR_EMAIL',
  TEST_ID_VALIDATION_ERROR_PASS: 'TEST_ID_VALIDATION_ERROR_PASS',
};

export const LANGUAGES_TESTS_IDS = {
  LANGUAGES_LIST: 'LANGUAGES_LIST',
  LANGUAGES_LIST_ITEM: 'LANGUAGES_LIST_ITEM',
};

export const CONTACTS_TESTS_IDS = {
  CONTACTS_LIST: 'CONTACTS_LIST',
  CONTACTS_LIST_ITEM: 'CONTACTS_LIST_ITEM',
  CONTACTS_LIST_ITEM_AVATAR: 'CONTACTS_LIST_ITEM_AVATAR',
  CONTACTS_LIST_ITEM_USERNAME: 'CONTACTS_LIST_ITEM_USERNAME',
  CONTACTS_LIST_ITEM_EMAIL: 'CONTACTS_LIST_ITEM_EMAIL',
  CONTACTS_LIST_ITEM_OCCUPATION: 'CONTACTS_LIST_ITEM_OCCUPATION',
  CONTACTS_EMPTY_TEXT: 'CONTACTS_EMPTY_TEXT',
};

export const SETTINGS_TESTS_IDS = {
  MARKER_RADIUS_LIST_ITEM: 'MARKER_RADIUS_LIST_ITEM',
  MARKER_RADIUS_INPUT: 'MARKER_RADIUS_INPUT',
  LANGUAGE_LIST_ITEM: 'LANGUAGE_LIST_ITEM',
  MODE_LIST_ITEM: 'MODE_LIST_ITEM',
  MODE_SWITCHER: 'MODE_SWITCHER',
  SETTINGS_LIST: 'SETTINGS_LIST',
};

export const PROFILE_TEST_IDS = {
  PROFILE_ITEMS_LIST: 'PROFILE_ITEMS_LIST',
  PROFILE_USERNAME: 'PROFILE_USERNAME',
};
