export const TESTS_IDS_LOGIN = {
  TEST_ID_EMAIL_INPUT: 'TEST_ID_EMAIL_INPUT',
  TEST_ID_PASSWORD_INPUT: 'TEST_ID_PASSWORD_INPUT',
  TEST_ID_SUBMIT_BUTTON: 'TEST_ID_SUBMIT_BUTTON',
  TEST_ID_REMEMBER: 'TEST_ID_REMEMBER',
  TEST_ID_VALIDATION_ERROR_EMAIL: 'TEST_ID_VALIDATION_ERROR_EMAIL',
  TEST_ID_VALIDATION_ERROR_PASS: 'TEST_ID_VALIDATION_ERROR_PASS',
};

export const LANGUAGES_TESTS_IDS = {
  LANGUAGES_LIST: 'LANGUAGES_LIST',
  LANGUAGES_LIST_ITEM: 'LANGUAGES_LIST_ITEM',
};

export const CAMERAS_TESTS_IDS = {
  CAMERAS_LIST: 'CAMERAS_LIST',
  CAMERA_LIST_ITEM: 'CAMERA_LIST_ITEM',
  CAMERA_LIST_ITEM_LOCATION: 'CAMERA_LIST_ITEM_LOCATION',
  CAMERA_LIST_ITEM_DESCRIPTION: 'CAMERA_LIST_ITEM_DESCRIPTION',
  CAMERA_LIST_ITEM_COORDINATES: 'CAMERA_LIST_ITEM_COORDINATES',
  CAMERAS_EMPTY_TEXT: 'CAMERAS_EMPTY_TEXT',
};

export const SETTINGS_TESTS_IDS = {
  MARKER_RADIUS_LIST_ITEM: 'MARKER_RADIUS_LIST_ITEM',
  MARKER_RADIUS_INPUT: 'MARKER_RADIUS_INPUT',
  LANGUAGE_LIST_ITEM: 'LANGUAGE_LIST_ITEM',
  MODE_LIST_ITEM: 'MODE_LIST_ITEM',
  MODE_SWITCHER: 'MODE_SWITCHER',
  SETTINGS_LIST: 'SETTINGS_LIST',
};

export const PROFILE_TEST_IDS = {
  PROFILE_ITEMS_LIST: 'PROFILE_ITEMS_LIST',
  PROFILE_USERNAME: 'PROFILE_USERNAME',
};
